### PR TITLE
feat(security): disable access for anonymous users, when disablePublicMemos is true

### PR DESCRIPTION
**Pull request by aatumaykin**
- Added check system.disablePublicMemos for non authorized users.
If user is anonymous and disablePublicMemos is on, then redirect to auth page 
- hide link to explore on sidebar for non authorized users.

### CODE REVIEW

**Comment by boojack** [comment]
Two design points:

* The `disablePublicMemos` is mainly used for new public memos created by users. For those existing old public memos, they will still be displayed on the explore page.
* The explore page should always be visible, whether logged in or not, just like someone's blog.

So is there some misunderstanding here, or do you have some other thoughts?

**Comment by aatumaykin** [comment]
> Two design points:
> 
> * The `disablePublicMemos` is mainly used for new public memos created by users. For those existing old public memos, they will still be displayed on the explore page.
> * The explore page should always be visible, whether logged in or not, just like someone's blog.
> 
> So is there some misunderstanding here, or do you have some other thoughts?

I think it should be possible to disable public access to all notes with one button. In my opinion, the disablePublicMemos setting can be used just for this. I make disablePublicMemos = true and all public memos become inaccessible to anonymous users. You need to be logged in to view them. At the same time, the visibility state in the notes themselves does not need to be changed.

There are only edits for the frontend, but in the future it will be necessary to finalize the backend. I also think that using id access to users and notes is a bad idea. You can sort through all the notes through brute force. From a security point of view, it is now considered good practice to use uuid identifiers.

**Review by boojack — APPROVED** [review]
LGTM

**Comment by boojack** [comment]
> I think it should be possible to disable public access to all notes with one button. In my opinion, the disablePublicMemos setting can be used just for this. I make disablePublicMemos = true and all public memos become inaccessible to anonymous users. You need to be logged in to view them. At the same time, the visibility state in the notes themselves does not need to be changed.
> 
> There are only edits for the frontend, but in the future it will be necessary to finalize the backend. I also think that using id access to users and notes is a bad idea. You can sort through all the notes through brute force. From a security point of view, it is now considered good practice to use uuid identifiers.

For the uid problem, we can use `username` instead of `id` for users in the routers. And add a `uuid` field to the memo model to replace the `id` in the router. In the backend, we should still keep using the `id`. WDYT?

Related issue: https://github.com/usememos/memos/issues/1916

**Comment by aatumaykin** [comment]
> > I think it should be possible to disable public access to all notes with one button. In my opinion, the disablePublicMemos setting can be used just for this. I make disablePublicMemos = true and all public memos become inaccessible to anonymous users. You need to be logged in to view them. At the same time, the visibility state in the notes themselves does not need to be changed.
> > There are only edits for the frontend, but in the future it will be necessary to finalize the backend. I also think that using id access to users and notes is a bad idea. You can sort through all the notes through brute force. From a security point of view, it is now considered good practice to use uuid identifiers.
> 
> For the uid problem, we can use `username` instead of `id` for users in the routers. And add a `uuid` field to the memo model to replace the `id` in the router. In the backend, we should still keep using the `id`. WDYT?
> 
> Related issue: #1916

Yes, I saw issue about username. I agree that username can be used. I haven't studied the code in detail, so I don't know if there is currently a uniqueness limit for username.

If the username is already unique, then there will be a minimum of problems with substitution in the url.

For memos and resources, you can generate a uuid based on id + salt (username or user id). This will greatly complicate brute force.

But all these changes are best done iteratively, with different commits/pull requests. Not in this PR. Many small PRs are better than one big one.

**Pull request merged**
