### PR TITLE
refactor: change all `Robot` to `Bot`

### PR DESCRIPTION
**Pull request by athurg**

### CODE REVIEW

**Review by Zeng1998 — CHANGES_REQUESTED** [review]
https://github.com/usememos/memos/blob/main/web/src/components/Settings/SystemSection.tsx#L153

**Comment by Zeng1998** [comment]
> https://github.com/usememos/memos/blob/main/web/src/components/Settings/SystemSection.tsx#L153

Not OpenAI. 🤣

**Comment by athurg** [comment]
That's not code relative to Telegram Bot and this PR. should I fixed here?

**Comment by athurg** [comment]
> web/src/components/Settings/SystemSection.tsx#L153

Fixed.

**Review by boojack — APPROVED** [review]
LGTM

**Pull request merged**
