### PR TITLE
Fix inverted color heatmap

### PR DESCRIPTION
**Pull request by Ni-g-3l**
Hey !

I fixed the heatmap color inversion describe here : [Issues 2104](https://github.com/usememos/memos/issues/2104) in order to be consistent with Github one.

### CODE REVIEW

**Comment by jxpsert** [comment]
Why is this closed?

**Comment by Ni-g-3l** [comment]
Someone already add this fix into his PR : https://github.com/usememos/memos/pull/2106

**Comment by jxpsert** [comment]
Oh, that's.. peculiar. That shouldn't have been done.

**Comment by Ni-g-3l** [comment]
oh sorry ! I won't do it anymore, it was just to prevent double work for reviewer

**Comment by jxpsert** [comment]
No no, you did fine. The other person shouldn’t have put 2 issues in one PR.

**Comment by Ni-g-3l** [comment]
I can reopen it, if you prefere merge fixes on by one

**Comment by jxpsert** [comment]
What’s done is done, let’s leave it as is.

**Pull request closed without merging**
