### PR TITLE
fix: v0.22.5: start fail caused by incorrect migration file naming

### PR DESCRIPTION
**Pull request by leo9800**
memos failed starting when using PostgreSQL as DB after upgrade to *v0.22.5*, which the following error message emitted: (docker installation, logs obtained by `docker logs memos`)

```
2024/09/03 15:18:39 ERROR failed to migrate error="strconv.Atoi: parsing \"00_reaction.sql\": invalid syntax\nfailed to convert patch version to int: 00_reaction.sql\ngithub.com/usememos/memos/store.(*Store).getSchemaVersionOfMigrateScript\n\tgithub.com/usememos/memos/store/migrator.go:233\ngithub.com/usememos/memos/store.(*Store).normalizedMigrationHistoryList\n\tgithub.com/usememos/memos/store/migrator.go:272\ngithub.com/usememos/memos/store.(*Store).preMigrate\n\tgithub.com/usememos/memos/store/migrator.go:151\ngithub.com/usememos/memos/store.(*Store).Migrate\n\tgithub.com/usememos/memos/store/migrator.go:37\nmain.init.func1\n\t./main.go:61\ngithub.com/spf13/cobra.(*Command).execute\n\tgithub.com/spf13/cobra@v1.8.1/command.go:989\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tgithub.com/spf13/cobra@v1.8.1/command.go:1117\ngithub.com/spf13/cobra.(*Command).Execute\n\tgithub.com/spf13/cobra@v1.8.1/command.go:1041\nmain.main\n\t./main.go:171\nruntime.main\n\truntime/proc.go:271\nruntime.goexit\n\truntime/asm_amd64.s:1695\nfailed to get schema version of migrate script\ngithub.com/usememos/memos/store.(*Store).normalizedMigrationHistoryList\n\tgithub.com/usememos/memos/store/migrator.go:274\ngithub.com/usememos/memos/store.(*Store).preMigrate\n\tgithub.com/usememos/memos/store/migrator.go:151\ngithub.com/usememos/memos/store.(*Store).Migrate\n\tgithub.com/usememos/memos/store/migrator.go:37\nmain.init.func1\n\t./main.go:61\ngithub.com/spf13/cobra.(*Command).execute\n\tgithub.com/spf13/cobra@v1.8.1/command.go:989\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tgithub.com/spf13/cobra@v1.8.1/command.go:1117\ngithub.com/spf13/cobra.(*Command).Execute\n\tgithub.com/spf13/cobra@v1.8.1/command.go:1041\nmain.main\n\t./main.go:171\nruntime.main\n\truntime/proc.go:271\nruntime.goexit\n\truntime/asm_amd64.s:1695\nfailed to normalize migration history list\ngithub.com/usememos/memos/store.(*Store).preMigrate\n\tgithub.com/usememos/memos/store/migrator.go:152\ngithub.com/usememos/memos/store.(*Store).Migrate\n\tgithub.com/usememos/memos/store/migrator.go:37\nmain.init.func1\n\t./main.go:61\ngithub.com/spf13/cobra.(*Command).execute\n\tgithub.com/spf13/cobra@v1.8.1/command.go:989\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tgithub.com/spf13/cobra@v1.8.1/command.go:1117\ngithub.com/spf13/cobra.(*Command).Execute\n\tgithub.com/spf13/cobra@v1.8.1/command.go:1041\nmain.main\n\t./main.go:171\nruntime.main\n\truntime/proc.go:271\nruntime.goexit\n\truntime/asm_amd64.s:1695\nfailed to pre-migrate\ngithub.com/usememos/memos/store.(*Store).Migrate\n\tgithub.com/usememos/memos/store/migrator.go:38\nmain.init.func1\n\t./main.go:61\ngithub.com/spf13/cobra.(*Command).execute\n\tgithub.com/spf13/cobra@v1.8.1/command.go:989\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tgithub.com/spf13/cobra@v1.8.1/command.go:1117\ngithub.com/spf13/cobra.(*Command).Execute\n\tgithub.com/spf13/cobra@v1.8.1/command.go:1041\nmain.main\n\t./main.go:171\nruntime.main\n\truntime/proc.go:271\nruntime.goexit\n\truntime/asm_amd64.s:1695"
```

Which gives error message as below, after unescaping `\t` and `\n`:

```
strconv.Atoi: parsing \"00_reaction.sql\": invalid syntax
failed to convert patch version to int: 00_reaction.sql
github.com/usememos/memos/store.(*Store).getSchemaVersionOfMigrateScript
	github.com/usememos/memos/store/migrator.go:233
github.com/usememos/memos/store.(*Store).normalizedMigrationHistoryList
	github.com/usememos/memos/store/migrator.go:272
github.com/usememos/memos/store.(*Store).preMigrate
	github.com/usememos/memos/store/migrator.go:151
github.com/usememos/memos/store.(*Store).Migrate
	github.com/usememos/memos/store/migrator.go:37
main.init.func1
	./main.go:61
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.8.1/command.go:989
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.8.1/command.go:1117
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.8.1/command.go:1041
main.main
	./main.go:171
runtime.main
	runtime/proc.go:271
runtime.goexit
	runtime/asm_amd64.s:1695
failed to get schema version of migrate script
github.com/usememos/memos/store.(*Store).normalizedMigrationHistoryList
	github.com/usememos/memos/store/migrator.go:274
github.com/usememos/memos/store.(*Store).preMigrate
	github.com/usememos/memos/store/migrator.go:151
github.com/usememos/memos/store.(*Store).Migrate
	github.com/usememos/memos/store/migrator.go:37
main.init.func1
	./main.go:61
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.8.1/command.go:989
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.8.1/command.go:1117
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.8.1/command.go:1041
main.main
	./main.go:171
runtime.main
	runtime/proc.go:271
runtime.goexit
	runtime/asm_amd64.s:1695
failed to normalize migration history list
github.com/usememos/memos/store.(*Store).preMigrate
	github.com/usememos/memos/store/migrator.go:152
github.com/usememos/memos/store.(*Store).Migrate
	github.com/usememos/memos/store/migrator.go:37
main.init.func1
	./main.go:61
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.8.1/command.go:989
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.8.1/command.go:1117
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.8.1/command.go:1041
main.main
	./main.go:171
runtime.main
	runtime/proc.go:271
runtime.goexit
	runtime/asm_amd64.s:1695
failed to pre-migrate
github.com/usememos/memos/store.(*Store).Migrate
	github.com/usememos/memos/store/migrator.go:38
main.init.func1
	./main.go:61
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.8.1/command.go:989
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.8.1/command.go:1117
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.8.1/command.go:1041
main.main
	./main.go:171
runtime.main
	runtime/proc.go:271
runtime.goexit
	runtime/asm_amd64.s:1695
```

This seems to be caused by the incorrect naming of `store/migration/postgres/prod/0.20/00_reaction.sql`, (**only 1 underline between `00` and `reaction`**) which should be `00__reaction.sql`. (**2 underlines**)

We could confirm by reading the recent-changed `store/migrator.go`, the constant `MigrateFileNameSplit` is defined as `__` and this constant is used when splitting the migrate files in function `getSchemaVersionOfMigrateScript()`.

### CODE REVIEW

**Comment by leo9800** [comment]
This issue may only affect those who run memos with postgresql, since I did not found similar naming error in mysql or sqlite migration files.

**Comment by Morethanevil** [comment]
And I wondered why it crashed :D

Guess I need to wait until it is fixed

**Review by boojack — APPROVED** [review]

**Comment by gabe565** [comment]
I just tested using `ghcr.io/usememos/memos:test@sha256:a6dc3674c1ef499dc0fa321f571299c76d0cf021a604e2e03cdb617fcb90cd80` and can confirm the issue is fixed. Thank you!

**Comment by Valen-C12** [comment]
When will it release, I use the neosmemo/memos:stable docker image and run into this issue yesterday. seems the issue still exist

**Comment by leo9800** [comment]
@Valen-C12 

> When will it release, I use the neosmemo/memos:stable docker image and run into this issue yesterday. seems the issue still exist

Try pull the docker image again. I personally use `ghcr.io/usememos/memos` (the default `latest` tag) in my production setup, the image has been rebuilt after this PR is merged.

Re-pulling and recreating the container would fix the issue.

**Comment by k3davis** [comment]
I had a new pull of the image but had to use `latest`, the fix doesn't seem to be in `stable` yet.

**Comment by dfface** [comment]
Thanks, use `latest` solve this.
But, `stable` tag still has the problem. Which did't worth the stable name.

**Comment by mariushosting** [comment]
@boojack any news? @RoccoSmit

**Comment by leo9800** [comment]
@mariushosting This patch should have been included in the latest `v0.23.0`.

**Comment by mariushosting** [comment]
> @mariushosting This patch should have been included in the latest `v0.23.0`, according to the changelog.

Thank you Leo!

**Comment by kamilmodest** [comment]
> This issue may only affect those who run memos with postgresql, since I did not found similar naming error in mysql or sqlite migration files.

I got similar issue with sqlite, but with different script name:

```
2025/01/31 18:30:11 ERROR failed to migrate error="strconv.Atoi: parsing \"00_memo_tags.sql\": invalid syntax
failed to convert patch version to int: 00_memo_tags.sql
```

Full trace:
```
2025/01/31 18:30:11 ERROR failed to migrate error="strconv.Atoi: parsing \"00_memo_tags.sql\": invalid syntax
failed to convert patch version to int: 00_memo_tags.sql
github.com/usememos/memos/store.(*Store).getSchemaVersionOfMigrateScript
    /backend-build/store/migrator.go:243
github.com/usememos/memos/store.(*Store).normalizedMigrationHistoryList
    /backend-build/store/migrator.go:282
github.com/usememos/memos/store.(*Store).preMigrate
    /backend-build/store/migrator.go:161
github.com/usememos/memos/store.(*Store).Migrate
    /backend-build/store/migrator.go:38
main.init.func1
    /backend-build/bin/memos/main.go:61
github.com/spf13/cobra.(*Command).execute
    /go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:989
github.com/spf13/cobra.(*Command).ExecuteC
    /go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117
github.com/spf13/cobra.(*Command).Execute
    /go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
main.main
    /backend-build/bin/memos/main.go:171
runtime.main
    /usr/local/go/src/runtime/proc.go:272
runtime.goexit
    /usr/local/go/src/runtime/asm_arm64.s:1223
failed to get schema version of migrate script
github.com/usememos/memos/store.(*Store).normalizedMigrationHistoryList
    /backend-build/store/migrator.go:284
github.com/usememos/memos/store.(*Store).preMigrate
    /backend-build/store/migrator.go:161
github.com/usememos/memos/store.(*Store).Migrate
    /backend-build/store/migrator.go:38
main.init.func1
    /backend-build/bin/memos/main.go:61
github.com/spf13/cobra.(*Command).execute
    /go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:989
github.com/spf13/cobra.(*Command).ExecuteC
    /go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117
github.com/spf13/cobra.(*Command).Execute
    /go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
main.main
    /backend-build/bin/memos/main.go:171
runtime.main
    /usr/local/go/src/runtime/proc.go:272
runtime.goexit
    /usr/local/go/src/runtime/asm_arm64.s:1223
failed to normalize migration history list
github.com/usememos/memos/store.(*Store).preMigrate
    /backend-build/store/migrator.go:162
github.com/usememos/memos/store.(*Store).Migrate
    /backend-build/store/migrator.go:38
main.init.func1
    /backend-build/bin/memos/main.go:61
github.com/spf13/cobra.(*Command).execute
    /go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:989
github.com/spf13/cobra.(*Command).ExecuteC
    /go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117
github.com/spf13/cobra.(*Command).Execute
    /go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
main.main
    /backend-build/bin/memos/main.go:171
runtime.main
    /usr/local/go/src/runtime/proc.go:272
runtime.goexit
    /usr/local/go/src/runtime/asm_arm64.s:1223
failed to pre-migrate
github.com/usememos/memos/store.(*Store).Migrate
    /backend-build/store/migrator.go:39
main.init.func1
    /backend-build/bin/memos/main.go:61
github.com/spf13/cobra.(*Command).execute
    /go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:989
github.com/spf13/cobra.(*Command).ExecuteC
    /go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117
github.com/spf13/cobra.(*Command).Execute
    /go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
main.main
    /backend-build/bin/memos/main.go:171
runtime.main
    /usr/local/go/src/runtime/proc.go:272
runtime.goexit
    /usr/local/go/src/runtime/asm_arm64.s:1223"
```

**Pull request merged**
