### PR TITLE
Delete .vscode directory

### PR DESCRIPTION
**Pull request by ambi88dex**

### CODE REVIEW

**Comment by Juneezee** [comment]
Could you explain why?

**Comment by ambi88dex** [comment]
> Could you explain why?

I was suggesting deleting .vscode directory because if we somebody wants to have custom configs in .vscode, they would be overidding the folder. Secondly, the .vscode property is something which shouldn't be part of source code as it is not source code.

**Comment by boojack** [comment]
`./web/.vscode` can also be deleted.

**Comment by ambi88dex** [comment]
Sure. I can add that folder as well in the PR

**Comment by ambi88dex** [comment]
Hi @boojack & @Juneezee , I've added the mentioned directories to be deleted.
Kindly give it a look!

**Review by boojack — APPROVED** [review]
LGTM, thanks for your contribution!

**Pull request merged**
