### PR TITLE
feat: support tag auto-completion

### PR DESCRIPTION
**Pull request by Zeng1998**
Please have a try and make some suggestions.

A relative simple implementation, maybe not working in some corner cases.

### CODE REVIEW

**Comment by ChasLui** [comment]
image
Would it be better to remove transparency from the Tag panel background color? Now I can see the `Only visible to you' in the lower level and it feels strange.

**Comment by ChasLui** [comment]
Press esc to close the tag panel

**Comment by ChasLui** [comment]
To prevent false triggers, should I use space+# as a match? For example, in github issue and flomo.

**Comment by Zeng1998** [comment]
> To prevent false triggers, should I use space+# as a match? For example, in github issue and flomo.

Hello, what do you mean about "space+#" ?

In github, when I type a "#"，the issue/pr selection panel are shown.

**Comment by ChasLui** [comment]
> > To prevent false triggers, should I use space+# as a match? For example, in github issue and flomo.
> 
> Hello, what do you mean about "space+#" ?
> 
> In github, when I type a "#"，the issue/pr selection panel are shown.

For example, I have a text `hello world`, when I type a `hello world#` at the end it doesn't show the tag panel, if I type `hello world #` then the tag panel appears.

**Comment by jxpsert** [comment]
> To prevent false triggers, should I use space+# as a match? For example, in github issue and flomo.

I think so, yes. You might want to use URLs that have # in them (think ``https://www.your.site/#about-me``).

**Comment by Zeng1998** [comment]
But when I just want to type #tag in one line.

Do you mean I should type one space before?

**Comment by ChasLui** [comment]
> 

The new line may require some special handling, in github the new line header can be touched by typing # in the tab panel

**Comment by Zeng1998** [comment]
Sorry I can't get the point. As the video show, there seems like no other trigger in github editor? (Just type one "#" is ok.)


https://user-images.githubusercontent.com/31177490/209596226-9ddbce18-5ecd-490e-840a-1c44b7ee163a.mp4

**Comment by ChasLui** [comment]
hello world www.baidu.com 

> Sorry I can't get the point. As the video show, there seems like no other trigger in github editor? (Just type one "#" is ok.)
> 
>  20221227_091612.mp4


https://user-images.githubusercontent.com/10083758/209618532-638148e9-07e3-4213-86dd-758cb6ed0798.mov

**Pull request closed without merging**
