### PR TITLE
Update de.json

### PR DESCRIPTION
**Pull request by Ghost108**
I used the en.json as a template and translated it (german language)
@boojack

### CODE REVIEW

**Comment by boojack** [comment]
@Ghost108 Thanks for your contribution! Please fix the JSON format error.

image

**Comment by Ghost108** [comment]
Yes I see it.
But how can I fix it?
my json file has online 400 lines. How can I see where there error is? 

sorry, thats my first time that I uploaded a file in github

**Review by boojack — APPROVED** [review]
LGTM, thanks for the contribution!

**Comment by Ghost108** [comment]
Your welcome! 
I am using the docker version. Can you tell me, when this update will be available?

**Comment by boojack** [comment]
> Your welcome! I am using the docker version. Can you tell me, when this update will be available?

To ensure the quality and completeness of the release, the earliest we can update maybe in this weekend, but possibly next weekend.

**Pull request merged**
